class Frameworks:
    frameworks = {
        "DJANGO": 0,
        "FLASK": 0,
        "FASTAPI": 0,
        "PYRAMID": 0,
        "SPRING": 0,
        "HIBERNATE": 0,
        "ASP NET": 0,
        "RUBY ON RAILS": 0,
        "SINATRA": 0,
        "LARAVEL": 0,
        "SYMFONY": 0,
        "CAKEPHP": 0,
        "ZEND": 0,
        "ANGULAR": 0,
        "REACT": 0,
        "VUE": 0,
        "NEXTJS": 0,
        "NUXTJS": 0,
        "SVELTE": 0,
        "EXPRESS": 0,
        "KOA": 0,
        "NESTJS": 0,
        "SPRING BOOT": 0,
        "PLAY": 0,
        "QUARKUS": 0,
        "DOTNET CORE": 0,
        "BLAZOR": 0,
        "IONIC": 0,
        "XAMARIN": 0,
        "QT": 0,
        "GTK": 0,
        "TKINTER": 0,
        "KIVY": 0,
        "UNITY": 0,
        "UNREAL": 0,
        "GODOT": 0,
        "PHASER": 0,
        "ELECTRON": 0,
        "CORDOVA": 0,
        "PHONEGAP": 0,
        "JQUERY": 0,
        "BOOTSTRAP": 0,
        "MATERIAL UI": 0,
        "TAILWIND": 0,
        "FOUNDATION": 0,
        "BULMA": 0,
        "TURBO": 0,
        "HOTWIRE": 0,
        "SAP UI5": 0,
        "VAADIN": 0,
        "STRUTS": 0,
        "GRAILS": 0,
        "MICRONAUT": 0,
        "JINJA": 0,
        "BOTTLE": 0,
        "CHERRYPY": 0,
        "WEB2PY": 0,
        "TORNADO": 0,
        "SANIC": 0,
        "PYLONS": 0,
        "TURBOGEARS": 0,
        "HUG": 0,
        "CELERY": 0,
        "BLAZOR SERVER": 0,
        "MAVEN": 0,
        "GRADLE": 0,
        "JEST": 0,
        "JASMINE": 0,
        "MOCHA": 0,
        "CYPRESS": 0,
        "SELENIUM": 0,
        "PLAYWRIGHT": 0,
        "NIGHTWATCH": 0,
        "ENZYME": 0,
        "TESTCAFE": 0,
        "CUCUMBER": 0,
        "PYTEST": 0,
        "UNITTEST": 0,
        "NOSE": 0,
        "ROCKET": 0,
        "ACTIX": 0,
        "YEW": 0,
        "SAPHYR": 0,
        "DJANGO REST FRAMEWORK": 0,
        "RESTIFY": 0,
        "LOOPBACK": 0,
        "FEATHERS": 0,
        "HAPI": 0,
        "METEOR": 0,
        "MOLECULER": 0,
        "SAPPER": 0,
        "MARKO": 0,
        "ALPINEJS": 0,
        "MOBX": 0,
        "REDUX": 0,
        "VITE": 0,
        "GRIDSOME": 0,
        "GATSBY": 0,
        "DOCUSAURUS": 0,
        "HEXO": 0,
        "HUGO": 0,
        "EMBER": 0,
        "BACKBONE": 0,
        "MARIONETTE": 0,
        "STIMULUS": 0,
        "PREACT": 0,
        "INFERNO": 0,
        "SOLIDJS": 0,
        "QWIK": 0,
        "STENCIL": 0,
        "MITHRIL": 0,
        "DOJO": 0,
        "SAP": 0,
        "EXTJS": 0,
        "SPRING MVC": 0,
        "STRUTS2": 0,
        "BLAZOR WEBASSEMBLY": 0,
        "SILVERLIGHT": 0,
        "WICKET": 0,
        "JSF": 0,
        "GWT": 0,
        "VAADIN FLOW": 0,
        "ZK": 0,
        "APACHE WICKET": 0,
        "APACHE TAPESTRY": 0,
        "APACHE COCON": 0,
        "PHOENIX": 0,
        "REACT NATIVE": 0,
        "FLUTTER": 0,
        "NATIVESCRIPT": 0,
        "MONO": 0,
        "KOTLIN MULTIPLATFORM": 0,
        "SWIFTUI": 0,
        "JETPACK COMPOSE": 0,
        "APPCELERATOR": 0,
        "FRAMEWORK7": 0,
        "ONSEN UI": 0,
        "SENCHA TOUCH": 0,
        "NWJS": 0,
        "WPF": 0,
        "WINFORMS": 0,
        "JAVA FX": 0,
        "SWING": 0,
        "GTKMM": 0,
        "WXWIDGETS": 0,
        "FLTK": 0,
        "SWT": 0,
        "TCL TK": 0,
        "TENSORFLOW": 0,
        "PYTORCH": 0,
        "KERAS": 0,
        "SCIKIT LEARN": 0,
        "THEANO": 0,
        "MXNET": 0,
        "CAFFE": 0,
        "PANDAS": 0,
        "NUMPY": 0,
        "MATPLOTLIB": 0,
        "SEABORN": 0,
        "DASK": 0,
        "R SHINY": 0,
        "DASH": 0,
        "STREAMLIT": 0,
        "BOKEH": 0,
        "PLOTLY": 0,
        "ALTAR": 0,
        "MONOGAME": 0,
        "LIBGDX": 0,
        "PANDA3D": 0,
        "LOVE2D": 0,
        "C2": 0,
        "CONSTRUCT": 0,
        "REN PY": 0,
        "URHO3D": 0,
        "CRYENGINE": 0,
        "OGRE3D": 0,
        "CORONA": 0,
        "COCOS2D": 0,
        "COCOS2DX": 0,
        "PIXIJS": 0,
        "JUNIT": 0,
        "NUNIT": 0,
        "RSPEC": 0,
        "TESTNG": 0,
        "AVA": 0,
        "TAPE": 0,
        "DOCTEST": 0,
        "BEHAVE": 0,
        "ROBOT FRAMEWORK": 0,
        "GINKGO": 0,
        "GTEST": 0,
        "CATCH2": 0,
        "BOOST TEST": 0,
        "APOLLO SERVER": 0,
        "GRAPHENE": 0,
        "GRPC": 0,
        "KONG": 0,
        "ZUUL": 0,
        "KRAKEND": 0,
        "API GATEWAY": 0,
        "AWS LAMBDA": 0,
        "WORDPRESS": 0,
        "DRUPAL": 0,
        "JOOMLA": 0,
        "GHOST": 0,
        "JEKYLL": 0,
        "ELEVENTY": 0,
        "NUXT": 0,
        "MIDDLEMAN": 0,
        "PELIGAN": 0,
        "NEXTRA": 0,
        "SERVERLESS": 0,
        "FASTIFY": 0,
        "KAFKA STREAMS": 0,
        "SPARK": 0,
        "FLINK": 0,
        "AIRFLOW": 0,
        "LUIGI": 0,
        "RQ": 0,
        "BEE QUEUE": 0,
        "BULL": 0,
        "SIDECIQ": 0,
        "ACTIX WEB": 0,
        "AXUM": 0,
        "POETRY": 0,
        "PIPENV": 0,
        "VITEPRESS": 0
    }
